services:
  db:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  poc:
    container_name: poc
    build: .
    volumes:
      - ./:/poc
    ports:
      - 3000:3000
    command: --reload --reload-dir poc --reload-include poc/*.py
    depends_on:
      - db
