"""
This file was autogenerated by Alembic.

Revision ID: 2a6411bd2710
Revises: 6df6b9c1eb46
Create Date: 2024-09-09 07:42:31.204153
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2a6411bd2710'
down_revision: str | None = '6df6b9c1eb46'
branch_labels: "str | Sequence[str] | None" = None
depends_on: "str | Sequence[str] | None" = None


def upgrade() -> None:
    """
    better cryptography
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groupings', 'encryption_key_nonce')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass