"""
This file was autogenerated by Alembic.

Revision ID: 50f8c42254d9
Revises: b2160fc5b54d
Create Date: 2024-09-07 07:29:27.481040
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50f8c42254d9"
down_revision: str | None = "b2160fc5b54d"
branch_labels: "str | Sequence[str] | None" = None
depends_on: "str | Sequence[str] | None" = None


def upgrade() -> None:
    """
    sharing model
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("host_user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "groups", "users", ["host_user_id"], ["id"])
    op.add_column("sharings", sa.Column("group_id", sa.Integer(), nullable=False))
    op.drop_constraint("sharings_user_id_fkey", "sharings", type_="foreignkey")
    op.create_foreign_key(None, "sharings", "groups", ["group_id"], ["id"])
    op.drop_column("sharings", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
