"""
This file was autogenerated by Alembic.

Revision ID: 6df6b9c1eb46
Revises: 6d10b2193f78
Create Date: 2024-09-09 05:17:28.254131
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6df6b9c1eb46'
down_revision: str | None = '6d10b2193f78'
branch_labels: "str | Sequence[str] | None" = None
depends_on: "str | Sequence[str] | None" = None


def upgrade() -> None:
    """
    better user key pairs
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encryption_key_salt', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass