"""
This file was autogenerated by Alembic.

Revision ID: 792c98a2edbd
Revises: e6d231a89924
Create Date: 2024-09-12 07:59:02.098330
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '792c98a2edbd'
down_revision: str | None = 'e6d231a89924'
branch_labels: "str | Sequence[str] | None" = None
depends_on: "str | Sequence[str] | None" = None


def upgrade() -> None:
    """
    add private col to groups
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('private', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass