"""
This file was autogenerated by Alembic.

Revision ID: b2160fc5b54d
Revises: 5c3396d70201
Create Date: 2024-08-30 04:45:17.608689
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b2160fc5b54d'
down_revision: str | None = '5c3396d70201'
branch_labels: "str | Sequence[str] | None" = None
depends_on: "str | Sequence[str] | None" = None


def upgrade() -> None:
    """
    add grouping nonce
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupings', sa.Column('encryption_key_nonce', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass