"""
This file was autogenerated by Alembic.

Revision ID: b3e0e6211624
Revises: bff06405ccb6
Create Date: 2024-08-29 05:32:04.209878
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b3e0e6211624'
down_revision: str | None = 'bff06405ccb6'
branch_labels: "str | Sequence[str] | None" = None
depends_on: "str | Sequence[str] | None" = None


def upgrade() -> None:
    """
    group name
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass