"""
This file was autogenerated by Alembic.

Revision ID: bff06405ccb6
Revises: b3631510525c
Create Date: 2024-08-28 05:49:34.709695
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bff06405ccb6'
down_revision: str | None = 'b3631510525c'
branch_labels: "str | Sequence[str] | None" = None
depends_on: "str | Sequence[str] | None" = None


def upgrade() -> None:
    """
    add content to items
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupings', sa.Column('encryption_key', sa.LargeBinary(), nullable=False))
    op.drop_column('groupings', 'group_encryption_key')
    op.add_column('items', sa.Column('content', sa.LargeBinary(), nullable=False))
    op.add_column('sharings', sa.Column('encryption_key', sa.LargeBinary(), nullable=False))
    op.drop_column('sharings', 'item_encryption_key')
    op.add_column('users', sa.Column('encryption_key', sa.LargeBinary(), nullable=False))
    op.drop_column('users', 'public_encryption_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass